# com o vim, <c-j> ou o g:vrc_trigger no método http
# https://github.com/diepm/vim-rest-console.git

# global definitions
// default host
http://localhost:3333

// argumentos curl default
-s # silencioso
#-i # header com syntax dinamica
--

--
POST /appointments
{
  "provider_id": "41677837-bd44-4720-93b1-a8223351bef2",
  "date": "2020-06-07T20:34:03"
}
--
GET /appointments
--
POST /users
{
  "name": "Diego Fernander",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}
--
POST /sessions
{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}
