# com o vim, <c-j> ou o g:vrc_trigger no método http
# https://github.com/diepm/vim-rest-console.git

# global definitions
// default host
http://localhost:3333

// argumentos curl default
-s # silencioso
#-i # header com syntax dinamica
// para testar rotas que precise estar logado (com token)
// -H @.vrc-token
// exemplo do arquivo:
// Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODg5MDU2NzksImV4cCI6MTU5NzM3Mjg3OSwic3ViIjoiYTk1ZDMzYTctZDdhZC00MWM4LWFlYjQtMGNhMTJkMjY2ZGMxIn0.8YdLVftEhzjx95b3Uqu2h4L6wg1o2wz3xbjE-GdJtbk

// Default headers.
--

--
POST /sessions
{
  "email": "diego@rocketseat.com.br",
  "password": "123123"
}
--
-H @.vrc-token
GET /appointments
--
POST /appointments
{
  "provider_id": "41677837-bd44-4720-93b1-a8223351bef2",
  "date": "2020-06-07T20:34:03"
}
--
POST /users
{
  "name": "Diego Fernander",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}
--
//-F avatar=@exemplo-avatar.jpg
// on windows
-F avatar=@"C:\Users\felip\Pictures\Camera Roll\ead.png"
Content-Type: multipart/form-data
-H @.vrc-token
PATCH /users/avatar
--
POST /password/forgot
{
  "email": "diego@rocketseat.com.br"
}
--
-d @.vrc-password-reset
POST /password/reset
//{
//  "password": "123123",
//  "token": "862fbcb1-a4c8-4007-b21a-985e8ea756f1"
//}
