# dicas:
#   - cursor no método http e <c-j>

# global definitions
// default host
http://localhost:3333

// argumentos curl default
-s # silencioso
#-i # header com syntax dinamica
--

--
POST /appointments
{
  "provider": "Felipe",
  "date": "2020-04-07T20:34:03"
}
--
GET /

